name: Tests

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: xdebug
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Install node dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
        run: npm install

      - name: Generate key
        run: php artisan key:generate


      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Build assets
        run: npm run dev

      - name: Tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: ./vendor/bin/pest
